# k8s/root/root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k8strainer/iac-workload.git
    targetRevision: main
    path: k8s/apps                 # <‑ Verzeichnis mit Application für GKE Workload cluster und AppSet für Core Services
    directory:
      recurse: true                # alle *.yaml Dateien einlesen
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
