---
apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: gke-demo
  namespace: team-a
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedCluster
    name: gke-demo
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedControlPlane
    name: gke-demo-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedCluster
metadata:
  name: gke-demo
  namespace: team-a
spec:
  project: cluster-01-290863
  region: europe-west4
  network:
    name: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: gke-demo-control-plane
  namespace: team-a
spec:
  project: cluster-01-290863
  location: europe-west4
  version: "1.32.4"
  releaseChannel: stable
  clusterName: gke-demo              # Cloud-Anzeige­name
  enableAutopilot: false
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: gke-demo-mp-0
  namespace: team-a
spec:
  clusterName: gke-demo
  replicas: 3
  template:
    spec:
      clusterName: gke-demo
      bootstrap:
        dataSecretName: "dummy-bootstrap"
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPManagedMachinePool
        name: gke-demo-mp-0
---
apiVersion: v1
kind: Secret
metadata:
  name: dummy-bootstrap
  namespace: team-a
type: Opaque
data: {}


---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePool
metadata:
  name: gke-demo-mp-0
  namespace: team-a
spec:
  # machineType: e2-standard-4
  ## if not set, default instance Type (2 CPUs, 8 GB RAM) is used
  diskType: pd-ssd
  diskSizeGB: 150
  scaling:
    enableAutoscaling: true
    maxCount: 6
    minCount: 3
