apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"         # Wave 1  →  nach Wave 0
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        # nur Cluster mit env=dev  ODER  env=staging
        - key: env
          operator: In
          values: ["dev", "staging"]
        # Nur team "a"
        - key: team
          operator: In
          values: ["a"]
      values:
        # Platzhalter für den Cluster Namen
        cluster_name: "{{ .name }}"
  template:
    metadata:
      name: core-services-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/k8strainer/iac-workload.git
        targetRevision: main
        path: k8s/core-services          
        directory:
          recurse: true                # alle *.yaml Dateien einlesen

      destination:
        server: "{{server}}"                 
        namespace: kube-system
      syncPolicy:
        automated: { prune: true, selfHeal: true }
